name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pywin32 requests pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "QLVT_Processor_v${{ github.ref_name }}" qlvt.py
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/QLVT_Processor_v${{ github.ref_name }}.exe
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## Changelog
          - Cập nhật tính năng xử lý phiếu
          - Cải thiện giao diện người dùng
          - Sửa lỗi xử lý bảng ký tên
          - Thêm hệ thống auto-update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 